name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Coverlet coverage test
        # You may pin to the exact commit or the version.
        # uses: b3b00/coverlet-action@ea67400f084993d98cfb3e2ec5948197d80a7d4e
        uses: b3b00/coverlet-action@1.1.1
        with:
          # output filename
          output: coverage.xml # default is ./lcov.info
          # output format : lcov, json, opencover, corbertura, temacity (see coverlet documentation)
          outputFormat: cobertura # default is lcov
          # assemblies, namespances exclusions (see coverlet documentation)
          # excludes: # optional
          # path to unit test project from repository root
          testProject: TDDWorkshop.Test/TDDWorkshop.Test.csproj
      - name: Codacy Coverage Reporter
        # You may pin to the exact commit or the version.
        # uses: codacy/codacy-coverage-reporter-action@53ebfe140c89720a8234b8ea4fabaf6de5736092
        uses: codacy/codacy-coverage-reporter-action@0.2.0
        with:
          # Project token for the Codacy project you want to send coverage information
          project-token: 0b97e4e9807848e48b4b992103f31f17 
          # Optional comma separated list of coverage reports to send to Codacy
          coverage-reports: TDDWorkshop.Test/coverage.xml
      - name: Codecov
        # You may pin to the exact commit or the version.
        # uses: codecov/codecov-action@9b0b9bbe2c64e9ed41413180dd7398450dfeee14
        uses: codecov/codecov-action@v1.3.2
        with:
          # Repository upload token - get it from codecov.io. Required only for private repositories
          token: 84c69d6d-96ac-4544-acd4-fedac2eb59fe # optional
          # Comma-separated list of files to upload
          files: coverage.xml # optional
          # Directory to search for coverage reports.
          directory: TDDWorkshop.Test # optional
          # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
          # flags: # optional
          # Path to coverage file to upload
          # file: # optional
