name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Coverlet coverage test
        # You may pin to the exact commit or the version.
        # uses: b3b00/coverlet-action@ea67400f084993d98cfb3e2ec5948197d80a7d4e
        uses: b3b00/coverlet-action@1.1.1
        with:
          # output filename
          output: report.json # default is ./lcov.info
          # output format : lcov, json, opencover, corbertura, temacity (see coverlet documentation)
          outputFormat: json # default is lcov
          # assemblies, namespances exclusions (see coverlet documentation)
          # excludes: # optional
          # path to unit test project from repository root
          testProject: TDDWorkshop.Test/TDDWorkshop.Test.csproj
